### ISSUE TITLE
Export stop working after 4100 videos.

### ISSUE THREAD

**Issue by SpellDreams** [sniklaus/youtube-watchmarker#1]
Export stop working after around 4100 videos. On export button click, after the incremental video count, page becomes white and keeps loading forever.

**Comment by sniklaus** [comment]
Thank you for bringing this up. I have realized this as well but it happens randomly and is not related to the number of videos. So far, I believe it is a problem within Firefox but I yet have to find the exact cause. In the meantime, the only thing I can suggest is to try it again every once in a while.

**Comment by sniklaus** [comment]
It looks like other developers are having the same issue: https://discourse.mozilla-community.org/t/bug-exporting-files-via-javascript/

**Comment by SpellDreams** [comment]
hello there!


I'm a fellow web developer.


I just have a hunch, that a small delay between the processing of the records and the file saving would fix this issue.


my 2 cents.

________________________________

**Comment by sniklaus** [comment]
Thank you for the hint! I just tried adding a `window.setTimeout(function() { ... }, 1000);` to the save code in: https://github.com/sniklaus/youtube-watchmarker/blob/master/content/index.js#L103

It does sadly still show the same behavior. I am currently waiting for the status of the bug report to investigate this further: https://bugzilla.mozilla.org/show_bug.cgi?id=1338981

Thanks again for mentioning it and for your suggestion!

**Comment by sniklaus** [comment]
I just changed the implementation in 0237624 and uploaded a new version, which should have fixed this issue. Thanks again!
