### ISSUE TITLE
Can't access the preferences window

### ISSUE THREAD

**Issue by Rua** [sniklaus/youtube-watchmarker#107]
On the page to manage the extension, the ... menu in the top right only has "remove" and "report" options. There is no "preferences" option, which is there for most extensions. I didn't even know there was supposed to be a preferences window, until I noticed the screenshot of it on the extension page.

Running Firefox 116.0.3 on Linux Mint.

**Comment by mark-wd** [comment]
> On the page to manage the extension, the ... menu in the top right only has "remove" and "report" options. There is no "preferences" option, which is there for most extensions. I didn't even know there was supposed to be a preferences window, until I noticed the screenshot of it on the extension page.
> 
> Running Firefox 116.0.3 on Linux Mint.

Instead of going to the Add-ons tab, open the puzzle icon and click on the extension there. This will pop-up the settings.

**Comment by Rua** [comment]
Ah, there it is. Thanks!
