### ISSUE TITLE
"YouTube sync" issue: finished at start again.

### ISSUE THREAD

**Issue by Almashina** [sniklaus/youtube-watchmarker#109]
Hi!
"YouTube sync" finished at start oct2023
It seems that this time the problem appeared after the auto-update of Mozilla ESR from 102.* to 115.* .
The number of synchronized videos does not grow from time to time. Like 36, then 54, then 45.
FF 115.3.1esr  |  watchmarker 4.3.1
![2023-10-08_125354](https://github.com/sniklaus/youtube-watchmarker/assets/54445863/506a065a-f93f-4f7d-a015-7d38e9ba39c3)

**Comment by Almashina** [comment]
**upd:**
I installed the portable version of FF 102.9.0 ESR and did the same: no problems as a result.
Now it’s clear that the problem appeared with the update of Mozilla to version 115.
![2023-10-09_193851](https://github.com/sniklaus/youtube-watchmarker/assets/54445863/a1f47afe-af14-449c-bdd6-146cdc0ffcf0)

**Comment by Almashina** [comment]
**upd2:**
I found out that:
- the latest version of Mozilla 102 is 102.12.0esr and it has **no** issue.
- the first version of Mozilla 103 is 103.0 and it has an issue.

**Comment by sniklaus** [comment]
Thanks for reporting this! I will fix it tonight and release a new version. Please feel free to reopen this issue should the problem persist after I released the next version.
