### ISSUE TITLE
When you click on it, it won't immediately show you the video you watched.

### ISSUE THREAD

**Issue by und2ad** [sniklaus/youtube-watchmarker#110]
This seems to be a problem that occurred after today's YouTube update.

**Comment by sniklaus** [comment]
Are you using Firefox or Chrome?

**Comment by sniklaus** [comment]
I just released version `4.4.2` which should address this issue. It is already available on Firefox and should make it to Chrome in roughly two days. I am hence closing this issue, and thanks for reporting it. Please don't hesitate to let me know in case it still is a problem even after the update.
