### ISSUE TITLE
Feature Request: Export history for FreeTube import

### ISSUE THREAD

**Issue by Jeefongithub** [sniklaus/youtube-watchmarker#112]
Requesting a possible export option to be formatted for import into freetube 

https://github.com/FreeTubeApp/FreeTube

**Comment by sniklaus** [comment]
Here is a Python script that converts a `.database` file to a generic `.json` file (make sure to update the paths).

```python
import base64
import json

with open('./backup.database', 'rb') as objFile:
    strIn = objFile.read()
# end

objVideos = json.loads(base64.b64decode(strIn))

with open('./backup.json', 'w') as objFile:
    objFile.write(json.dumps(objVideos))
# end
```

You can use this example (and/or the resulting JSON file) to convert the list of videos to whatever FreeTube requires. :+1:
