### ISSUE TITLE
Suggestion: Infinite-scrolling History

### ISSUE THREAD

**Issue by metal450** [sniklaus/youtube-watchmarker#12]
I found this addon while looking for a way to store my youtube watch history locally, so I can disable the watch history in my Google account, for privacy reasons. Although it wonderfully handles the task of marking videos as watched, it would be awesome if it provided a way to scroll through more than just the last few watches (at the bottom of its config page). At present, it seems to be limited to 10 items. Something like "load next page," and perhaps configurable "items per page" (so we could show more than 10) would be great :)

**Comment by sniklaus** [comment]
I implemented a quick fix which is ... drum rolls ... showing 100 instead of just 10 videos. This is inferior to infinite scrolling or having this parameter configurable but it was a very easy change for me. :smile: 

I am hence closing this issue for now. Thanks for bringing it up, the new behavior should definitely be more useful for more people.

**Comment by metal450** [comment]
Hi sniklaus,

Thanks for the reply :) While 100 is definitely better than 10, it does still only permit you to look back at the very short-term history.  If infinite scrolling is more challenging, perhaps just some next/previous buttons that let you flip through paging. i.e. if you're trying to find something by name you can search, but if you're trying to find something you looked at "last month," there's still no way to get to it.

Cheers!

**Comment by metal450** [comment]
(aka I don't think this issue should really be closed yet)

**Comment by sniklaus** [comment]
Fair enough, I did not consider the "browsing through the last month" use case. Reopening.

**Comment by mkruer** [comment]
Would this be better to add in a second page for just the history? I could see this being expanded out with more functionally at a later time, sort for videos that were opened but not really watched?  

Use Case: I opened up a bunch of videos (15-20) in tabs to watch later over a two week period, Somewhat ironically accidentally closed them looking into issue #32. If there was a good way to track the percentage watched #18. Then you could add in an option for "under watched" videos?

**Comment by sniklaus** [comment]
It sounds like adding an additional state parameter for each video in the database could be useful ("opened", "watched according to Youtube"). I am afraid that I am reluctant to make such feature changes at the moment, let me share my point of view. As far as I am aware, the extension satisfies typical users of Youtube. Supporting more unusual use cases leads to the code becoming more complex and hence more difficult to maintain. Both of which takes additional time that I unfortunately do not have.

**Comment by mkruer** [comment]
This is a "nice to have", not a requirement. I totally understand not wanting to add in more and more superfluous features. With youtubes constant changing of the front end, and some of the back end, I totally get not wanting to go down this path. 

The biggest challenge would be with YouTube v3 API as you need to register with them and I am not sure if they would like having a bunch of extensions  hitting their backed with a bunch of requests. Still if for some reason you needed to, then adding this would be relatively minor.  Just something to keep this in mind.

I think a compromise that might be able to be added what I started in #18, but drop the percentage and just add in time watched by grabbing the timestamp of the playing video every 5-10 seconds or so.

**Comment by sniklaus** [comment]
I just wanted to be upfront and honest about how I feel about it. :slightly_smiling_face: 

The initial release of the Youtube Watchmarker several years ago actually straight up used the official YouTube API and hence already had the authentication workflow implemented. However, Google does really not want you to export your watch history, I cannot see any other reasons why bugs like these prevail: https://issuetracker.google.com/issues/35172816

Grabbing for how long a video has been playing sounds nontrivial, do you have any Javascript to share that obtains that information?

**Comment by mkruer** [comment]
I totally understand, I am not a big fan of youtube's backbox approach to a lot of things. I prefer to have ultimate control of my data then any big tech, but that's beyond the scope of this bug.

You might want to look at 
https://tutorialzine.com/2015/08/how-to-control-youtubes-video-player-with-javascript
and see if this works, if it doesn't i need to dig harder  (non API way)

Like finding answer to the length of the video question, without requirement the use of the API.

In the HTML within the script of the page 
```  <div id="player" class="skeleton theater">
      <div id="player-api" class="player-width player-height off-screen-target player-api"></div>
```
look for 
`\"approxDurationMs\":\"828882\"`
where 828882 is the length of that video. (in this case ~829 seconds or 13minutes and 48 seconds.

**Comment by sniklaus** [comment]
Thank you for the link, I am afraid that the article is outdated by now. For example, it is no longer called `player` but `ytplayer` instead. While the `approxDurationMs` is still in the HTML, it doesn't tell you anything about the current state of the player (for how long at has been playing).

**Comment by mkruer** [comment]
According to the googles youtube API doc, https://developers.google.com/youtube/iframe_api_reference `player.getCurrentTime():Number` and `player.getDuration():Number` should still be reverent. However doing a quick search on the subject, Stackoverflow, https://stackoverflow.com/questions/22844507/getcurrenttime-for-youtube-video

> To make a minimal example, you can have a file `inject.js`
> 
> ```
> ytplayer = document.getElementById("movie_player");
> ytplayer.getCurrentTime();
> ```
> 
> And in your background page script, you can inject that into the current page as follows (when the button is clicked, for instance)
> 
> ```
> chrome.browserAction.onClicked.addListener(function(tab) {
>   chrome.tabs.executeScript({
>     file: 'inject.js'
>   });
> });
> ```
> 
> Then, you'll see the result of the exeution in the console of the currently open page. To report the result back, you'll need to use `chrome.runtime.sendMessage`

This might work better. if you want to bypass the API

**Comment by sniklaus** [comment]
`document.getElementById("movie_player").getCurrentTime()` would work, thanks!

**Comment by mkruer** [comment]
Not a problem. I am on my fourth or fifth doctorate on internet searching.

**Comment by sniklaus** [comment]
Infinite scrolling has now been added to version 4.1.0 so I am closing this issue for now. Thanks again for bringing this up!
