### ISSUE TITLE
"appears in the browser's history" option not working

### ISSUE THREAD

**Issue by piecevcake** [sniklaus/youtube-watchmarker#131]
When "Mark a video as watched once it appears in the browser's history." is selected, videos aren't marked when they are in the history.
(This option doesn't lag YT but doesn't mark the videos)

When you click sync history, the videos are added then they are marked.

**Comment by sniklaus** [comment]
The extension only syncs with the browser's history once every hour (code reference below for completeness).

https://github.com/sniklaus/youtube-watchmarker/blob/970f6d0ce0ea8e7b9fc89c5e947e5cf06ce2886f/background.js#L1956

If you want it sooner than that, then check "mark a video as watched once it has been opened in the browser". :+1:
