### ISSUE TITLE
[question] interaction with youtube api?

### ISSUE THREAD

**Issue by AlJohri** [sniklaus/youtube-watchmarker#14]
can I mark a video as watched and have it registered in youtube's watch history? I may have watched a video on another comptuer / incognito / etc and I just want to click a button to mark it as watched in YT's watch history

can this addon do this?

thanks!

**Comment by allanlaal** [comment]
YTs watchtime endpoints rely on specific playback ids and have quite a lot of anti-tampering protection:  https://github.com/OsaSoft/youtube-better-subscriptions/issues/38#issuecomment-425374091

**Comment by sniklaus** [comment]
Thank you for bringing this up! According to the link that Allan shared, it seems like there is quite a bit of tamper protection that makes it very difficult to implement this feature. I am hence holding off from adding it since it would probable take a huge chunk of my spare time, my apologies.
