### ISSUE TITLE
[Question]¿Is there a way to remove the watched label from the main window?

### ISSUE THREAD

**Issue by capitanjal** [sniklaus/youtube-watchmarker#15]
I'm using YouTube plus
https://github.com/ParticleCore/Particle/releases
and when i use the pop-out feature the watched label appear in the middle of the screen, is there a way to hide it it really bothers me but i really like your plugin to just disable it

**Comment by sniklaus** [comment]
Thank you for your suggestion! I am happy to announce that I just released a new version of the extension where you can remove the label in the options.
