### ISSUE TITLE
A wish for Youtube Watchmarker

### ISSUE THREAD

**Issue by Helgi123** [sniklaus/youtube-watchmarker#16]
Please, make it so that I can delete records older than 30 days from the database of the watched video as in Windows Media Player settings.
Thank you very much.

**Comment by Helgi123** [comment]
![default](https://user-images.githubusercontent.com/43931967/46671084-8803e380-cbdc-11e8-8745-e34681cec4d6.png)

**Comment by sniklaus** [comment]
Thank you for your suggestion! I am not sure what the purpose of the extension would be then. Youtube already marks recently seen videos as watched, the purpose of this extension is to also mark videos as watched that have been seen a long time ago. If only recently seen videos should be marked as watched, then Youtube itself already does this for you. I am hence closing this issue for now, please let me know in case I misunderstood something.
