### ISSUE TITLE
[Request] Only mark video as watched after video actually starts playing

### ISSUE THREAD

**Issue by vzjrz** [sniklaus/youtube-watchmarker#18]
I open a lot of youtube tabs from my subscriptions and sometimes I don't end up watching all of them but they are still marked as watched. I'm also using https://github.com/ParticleCore/Particle/ which prevents videos from autoplaying until I click them. So as you can see sometimes many videos are set as watched when I have not actually started watching them. It would be a great if your addon waited until the video started playing a few seconds before marking it as watched. Also, a simple way to mark a video as **unwatched** from the video page would help a lot. Thanks for the great addon!

**Comment by mkruer** [comment]
One way to address this might be by capturing the time code in the background as the video plays

URL 
https://www.youtube.com/watch?v=pPBKBOuyYPI

capture embedded timecode
https://youtu.be/pPBKBOuyYPI?t=54 

URL + timecode
https://www.youtube.com/watch?v=pPBKBOuyYPI?t=54

Then if we can get the length of the video, a simple time watch / full time -would be the percentage of the video watched. 

The only issues might be
Videos that are already in your history would not have this.
Videos that are being lived streamed would not have an end time.

**Comment by sniklaus** [comment]
The next version will include an option to only mark videos as watched if the appear in Youtube's watch history. They only appear on Youtube's watch history if they have actually been played for a while, which is not a perfect solution but it is easy for me to integrate it like this. :+1:

**Comment by sniklaus** [comment]
I just uploaded a new version with a "Condition" setting. Simply uncheck "Consider a video as watched once it appears in the browser's history." and videos will only become marked as watched once Youtube considers then as watched. As such, simply opening a video will not be sufficient to trigger it to be watched. Closing this issue for now, please let me know in case this new feature does not behave as expected. Thanks!

**Comment by mkruer** [comment]
Just an FYI, "imported 26835 videos - 21463 were new" And I am seeing in the youtube feed some of the videos recommended are now marked as watched that were not before. Thanks for the fix

**Comment by mkruer** [comment]
This is not a high priority. I don't use Youtube's watch history, so at some point you may need to revisit this with a solution not requiring Youtube's watch history.

**Comment by sniklaus** [comment]
I will make the settings more fine-grained in the next version. :+1:

**Comment by johsoderi** [comment]
> I will make the settings more fine-grained in the next version. 👍

I'd be so happy if there was a condition setting for % of video watched! Personally I'd like to fine-tune it between 85-95%.
I realise it may be a lot of work to implement though (and I'm not good with JS, so wouldn't be much help), but if you're working on something like that you'll have one happy freeloader here!

Either way, I really appreciate the work you're putting into this. I was going berserk at YT's "Up next" queue putting on mostly stuff I've already seen, but now I can look to the right of the video without risking a brain aneurysm <3
