### ISSUE TITLE
Wrong markings

### ISSUE THREAD

**Issue by ClayDragon** [sniklaus/youtube-watchmarker#2]
Until a couple of days ago I was very happy with your add-on, but recently it wrongly marks videos as being watched; this seems to happen especially often with newly uploaded videos. I have been using the new YouTube design and the Dark Theme since about the same time I have been experiencing these issues, so there could be a connection. Haven't looked into your code, but maybe YouTube (in new design mode) preloads newly uploaded videos and the add-on marks them as being watched? I will sadly have to disable the add-on until this problem is fixed. :(

**Comment by sniklaus** [comment]
Thank you for bringing this up!

The new design does unfortunately reuse certain elements. When you visit a page the first time, all the markers should be correct. But once you navigate around, the new design might reuse elements that were previously marked as watched and thus might incorrectly show a new video as already watched.

The good news is though, that your watch history should not be corrupted by this and a video that you have not watched before will not be marked as watched within the database. Once you refresh the page with the incorrect markers, the markers should be correct again. Can you confirm this or does it behave differently for you? Thanks!

**Comment by ClayDragon** [comment]
Thanks for the reply!

I tested it a bit more with some videos. As you said, after navigating from video to video for a while, unseen videos get marked. Once I spotted this, I exported my database, converted it back to readable JSON and grepped (I use Linux) for the unseen Video ID. True, it wasn't there. But then I closed the current (that I was watching) video tab, quit the browser and restarted it and opened the same ("current") video again in a new tab. The unseen video was still marked. I dumped the database again and now found the Video ID inside (with an empty string for the "strTitle" key, which might be a clue?). The timestamp seems to indicate I watched the unseen video a few minutes before navigating to the "current" video, but I'm not sure, I didn't particularly pay much attention to the timing.

I hope that helps! Thanks for the support so far! :)

**Comment by sniklaus** [comment]
Thank you again for your message and my apologies for the delayed response. I have just uploaded a new version that should behave more nicely with the new design. Please let me know in case you are still experiencing issues with it after receiving the updated version. I will close this issue in the meantime, thank you!

**Comment by ClayDragon** [comment]
Sorry for the very long delay here too!

Thank you for the fix, I've been using your add-on for months now and it seems to work as expected. Incidentally a couple of days ago the small bug you mentioned before happened to me, all videos were marked as watched in the right side bar on a YouTube video page, but after a page reload it went back to normal (the unwatched videos were unmarked again). That was just a lone incident after many months of watching videos, so I can live with that non-corrupting behavior.

Thanks again!

**Comment by sniklaus** [comment]
I am happy to hear that it works without any serious issues now. :)
