### ISSUE TITLE
Can't remove any video from watch later list on Firefox 63.0.3

### ISSUE THREAD

**Issue by Notare** [sniklaus/youtube-watchmarker#20]
In the watch later list next to the video page, not the own watch later page.
I mean, this https://i.imgur.com/ZrovzWS.jpg

**Comment by sniklaus** [comment]
Thank you for letting me know! I have noticed this issue for a while and will make sure to address it in the next version of the addon. I am pretty busy at the moment due to getting my degree, but I still care about this extension and am planning to give it a revamp!

**Comment by sniklaus** [comment]
I am happy to announce that the new version of the addon addresses this issue. Thanks again for bringing this up and please let me know in case the problem has not been fixed.
