### ISSUE TITLE
watched-badge appears on top of fullscreen videos

### ISSUE THREAD

**Issue by sniklaus** [sniklaus/youtube-watchmarker#22]
A user reported in their review that the watched-badge appears on top of fullscreen videos, which should not be the case: https://addons.mozilla.org/en-US/firefox/addon/yourect/reviews/1320419/

**Comment by Ligands** [comment]
I experienced this once or twice, and have confirmed the cause by checking the HTML source- it occurs when you're watching through a youtube **playlist** & there are videos on the playlist that you've already watched. The 'watched' badge for every item in the playlist (that's been watched before) moves to the top-left of the fullscreen window when you go fullscreen.

Happy to provide more detail / screenshots if necessary.

**Comment by sniklaus** [comment]
That is awesome, thank you for providing these crucial details! It is definitely going to help me address this issue when I finally find some time to revamp this extension!

**Comment by Ligands** [comment]
No worries, thank you for creating this nifty extension & improving the lackluster youtube UI :)

**Comment by Almashina** [comment]
Hello dear **sniklaus**!
It's really annoying to see this "watched" watermark on top of fullscreen videos.
It appears in playlists only in watched videos.
Some people open a video at first, then add that video to playlist "watch later" or another one, only after that start watching playlist in fullscreen - and badge appear in playlist's previously touched videos.
It must not be appeared on playing video at all.
Please, fix this bug, ftgj
![2019-08-23_200002](https://user-images.githubusercontent.com/54445863/63603612-6c7ead00-c5e3-11e9-87c6-4cd4ec9bbfac.jpg)

Thank You!

**Comment by sniklaus** [comment]
Thank you for the input! I understand that this is an important bug that has to be fixed and will do so in the next version.

**Comment by sniklaus** [comment]
Thanks again for bringing this up, I just released a new version with a fix. I am hence closing this issue for now, please let me know in case the problem still prevails.
