### ISSUE TITLE
Cross-device youtube synchronization failing

### ISSUE THREAD

**Issue by Ligands** [sniklaus/youtube-watchmarker#23]
Until recently, I've been having to run the youtube synchronize feature manually in order to get the correct watchmarkers from videos viewed on my work PC. (My work uses a company VPN which makes my connection appear as though it's in a different country, and therefore timezone, to where I actually live- not sure if it's related, but thought it might be important to note.)

However, in the last few days, the manual synchronize button (for the cross-platform 'youtube' sync, specifically) is no longer working- it looks like it's doing something for a few seconds, then just gives up & says "_finished synchronizing_", though the process fails consistently.
Screenshot for context:
![image](https://user-images.githubusercontent.com/3400211/58072239-2b958780-7bf3-11e9-940a-56ca8bdabe22.png)

Presumably related to the latest update to the Youtube website (which added a slightly different responsive view for desktop browsers resized to <1000px or so).

**Comment by sniklaus** [comment]
This is likely due to the latest update as you suggested. I am still using the old YouTube theme so I didn't notice yet. Please remind me if I haven't gotten around to issuing a quick fix for this within the next month. Thanks!

**Comment by hackabletype** [comment]
> Please remind me if I haven't gotten around to issuing a quick fix for this within the next month. Thanks!

Friendly reminder :)

**Comment by sniklaus** [comment]
My apologies about the delay. I just released an update that should have fixed this issue. Thanks again for bringing this up, please let me know in case the problem persists.
