### ISSUE TITLE
Display error on main youtube page

### ISSUE THREAD

**Issue by H4rm10d** [sniklaus/youtube-watchmarker#24]
Youtube has changed something in the design of the main page, the addon no longer displays the watched mark correctly.

**Comment by sniklaus** [comment]
Thank you for bringing this to my attention! I consider this to be pretty serious so I will definitely address it in the next version. Thanks!

**Comment by H4rm10d** [comment]
Thanks for fixing it back in August, however youtube.com made some changes and broke it again :/

**Comment by sniklaus** [comment]
This issue should have been fixed in the new version that I just released. I am hence closing this issue for now, please let me know in case the problem still prevails. Thanks!
