### ISSUE TITLE
Videos marked as watch because of previous searches.

### ISSUE THREAD

**Issue by pasi123567** [sniklaus/youtube-watchmarker#25]
I don't know if anyone reported an issue like this but I have this problem for like 3 months now.
If I search videos and click on some of them and afterwards search a different thing, then the newly shown videos have the same videos marked as watched as the previous search. 
I mean that the watched videos information does not update after changing the search term.
Only way I go around this right now is search something new and then also refresh the page, after that I get the new information
![weird bug](https://user-images.githubusercontent.com/12584747/66385785-5f662380-e9c1-11e9-944b-8a558e113e43.png)

**Comment by sniklaus** [comment]
Thank you for bringing this to my attention and for the detailed description! This is a side-effect of YouTube trying to reuse DOM / HTML elements, which by the way is something that they do not do in the old YouTube style. So you could switch to the old theme as a temporary workaround. I have tried to monkey-patch all situations where this reuse may happen in the new layout but my approach is not holistic. So thank you again for bringing this to my attention, I will have to find a more seminal way to handle all the different cases in the future!

**Comment by sniklaus** [comment]
I am happy to announce that I just released a new version where the integration into Youtube is done a little bit more robustly. This problem should hence be fixed and I am closing this issue for now. Thanks again for bringing this up and please let me know in case the problem still persists.
