### ISSUE TITLE
YouTube Changed Something in Main Page Causing Display Issues.

### ISSUE THREAD

**Issue by MarkRH** [sniklaus/youtube-watchmarker#26]
Firefox 70 and version 3.0.2 of the plugin.  With it active, YouTube now looks like:
![image](https://user-images.githubusercontent.com/8035962/67614786-58dcf780-f788-11e9-9afa-0ffc2d1b18bb.png)

When I Disabled Watchmaker, it looks like:
![image](https://user-images.githubusercontent.com/8035962/67614796-7dd16a80-f788-11e9-9a06-cabe516b4a0e.png)

**Comment by MarkRH** [comment]
Hmm.. doesn't do this in Firefox 71 beta though.

**Comment by sniklaus** [comment]
Thank you for bringing this to my attention! I am still on Firefox 70 and am not experiencing this. I am thus happy to hear that it went away on Firefox 71 on your end, maybe it was an issue unrelated to this extension? I am keeping this open for now in case someone else runs into the same issue, please keep me updated!

**Comment by MarkRH** [comment]
Well, I tried a clean profile with only uBlock Origin and YouTube Watchmaker installed and YouTube still looks messed up in version 70.  So, I'm pretty sure it's not an extension or userChrome.css conflict.

Well, I was just able to replicate the problem in 71 beta.  It is somehow tied to my YouTube account.  If I log in with my account in beta, then I get the messed up display.  If I log out in version 70, I don't get the problem. So... it's some setting within my YouTube account apparently.

**Comment by sniklaus** [comment]
Thank you for tracking down the origin of this problem! This is rather odd, the underlying structure of the page must have changed slightly. Since it is tied to your account, it is rather difficult for me to replicate and resolve this issue though. 🤔

**Comment by MarkRH** [comment]
Doh.. see above.  With a clean profile and not logged in, it's messed up in 70.  But, the page display is different.

**Comment by sniklaus** [comment]
My bad, I will try to replicate it once I have more spare time at my hand again. 👍

**Comment by MarkRH** [comment]
Man, I don't get it.  With my account I only get 4 thumbnails across but with a different account I have, I get 5 thumbnails across.

**Comment by MarkRH** [comment]
Well, I corrected the appearance using Stylish overrides:

```css
ytd-rich-grid-renderer {
	--ytd-rich-grid-items-per-row: 5 !important;
	--ytd-rich-grid-non-videos-per-row: 3 !important;
}

ytd-thumbnail {
	display: inline-flex !important;
}
```
Back to having 5 thumbnails per row and no weird grey box above it.  Really hate this new page design.

**Comment by sniklaus** [comment]
Thank you for sharing this!

**Comment by Almashina** [comment]
Hi guys!
I've got the same issue. 
Youtube send me an pop-up window about improvements of the main page and then this happen.
Firefox 56.0.2, addon 3.0.2

**Comment by Almashina** [comment]
[url=https://ibb.co/MfSgt1b][img]https://i.ibb.co/MfSgt1b/2019-11-10-115154.png[/img][/url]
Issue can be solved by changing youtube main page theme to the classical view (old layout, a bit anchient) with the "youtube design preserver" addon, but it is partial solution not for all.

**Comment by Almashina** [comment]
[url=https://ibb.co/MfSgt1b][img]https://i.ibb.co/w7gdPQT/2019-11-10-115154.png[/img][/url]
Issue can be solved by changing youtube main page theme to the classical view (old layout, a bit anchient) with the "youtube design preserver" addon, but it is partial solution not for all.

**Comment by Almashina** [comment]
Issue can be solved by changing youtube main page theme to the classical view (old layout, a bit anchient) with the "youtube design preserver" addon, but it is partial solution not for all.

**Comment by Almashina** [comment]
![2019-11-10_115154](https://user-images.githubusercontent.com/54445863/68540498-ec334100-03b4-11ea-88df-dce875c38c29.png)

**Comment by Almashina** [comment]
Hotfix with the styles override doesn't work correctly in my case with FF 56.0.2:
![2019-11-11_204811](https://user-images.githubusercontent.com/54445863/68600924-2855c700-04c5-11ea-98fe-50a5fe54afb2.jpg)

**Comment by sc113** [comment]
Same here, youtube turned on the new design for me today and it's bugged now.

**Comment by wooziwoozi** [comment]
Just here to say I got the YouTube update and I am having the same problem.

I have Firefox 70.0.1 (64-bit)

Disabling your add-on fixes the problem.

**Comment by Almashina** [comment]
Dear [b]wooziwoozi[/b], thank You, this fix works well for me (FF56.0.2) with "Stylus" addon.

**Comment by Almashina** [comment]
Dear wooziwoozi, thank You, this fix works well for me (FF56.0.2). I used "Stylus" addon.

**Comment by tntvenion** [comment]
Got the same problem after Youtube update was rolled out for me (ff 70.0.1, addon 3.0.2). I actually like the new Youtube style (probably since I have a big 32 inch 4k monitor). Had to disable the addon.

**Comment by sc113** [comment]
So.. why is it still didn't get updated yet? Is extension abandoned and I should uninstall it?

**Comment by mnkor** [comment]
> 
> 
> So.. why is it still didn't get updated yet? Is extension abandoned and I should uninstall it?

Theres a workaround above...

**Comment by wooziwoozi** [comment]
> 
> 
> So.. why is it still didn't get updated yet? Is extension abandoned and I should uninstall it?

Dude, chill out. It has only been 26 days since you complained it was broken. It has also been the Holiday season. People have lives and are busy. Sniklaus has always been great about updating their addons, so please learn some patience and leave your entitlement somewhere else. He doesn't owe us anything.

Also, scroll up, as mnkor said, I provided a temporary fix.

**Comment by sniklaus** [comment]
Thank you for your supporting words @mnkor and @wooziwoozi.

I acknowledge that this project is not in the best state at the moment but am committed to give it a revamp once I am less busy. I am afraid that I currently need to focus on my dissertation though. I also have not run into this issue on my end yet, which makes it pretty difficult to debug.

**Comment by mnkor** [comment]
For what its worth, I'm on 71.0. Just tried the following:
- Clear all cache/browsing history
- Disabled all extensions. 
- Changed DPI Scaling from 125% to 100%
- Tiles are bugged regardless of being logged in or not.

Currently on Windows 10 v1903 (18362.476)

About to download the Beta and see what that does for me.

**Comment by jpmb76** [comment]
I have same problem as MarkRH. On main page (youtube.com) I get these weird thumbnails. After running style suggested by MarkRH I have encountered same results as Almashina. Fix sugested by wooziwoozi did work for me. Also what worked for me was editing/creating PREF cookie with "f6=8" which brings back old youtube layout as described [here](https://www.quora.com/How-do-I-restore-the-old-YouTube-layout).

For those interested I'm on Ubuntu 18.04 running Waterfox Classic 2019.12 64-bit with following add-ons:
Adblock Plus 2.8.2
Adblock Plus Pop-up Addon 0.9.2.1-signed.1-signed
Analog Clock 1.6
Better Reader	8.3
Bitwarden - Free Password Manager 1.41.0
ChromEdit Plus 2.9.10
Context Search 0.6.4
Cookies Manager+	1.14.3
Disconnect 5.19.3
Download Manager (S3)	4.13
Element Hiding Helper for Adblock Plus 1.4
Enhancer for YouTube™	2.0.99
Flagfox 5.2.3
Gmail Watcher	2.29
GNOME Shell integration	10.1
Go Parent Folder 2.9.1.1-signed.1-signed
Greasemonkey 4.1
In My Pocket 0.10.6
Keybinder 2.0.5
Linkificator 3.2.1
Menu Wizard 5.10
QuickMark 1.2.11
Restart 3.0.2
Shareaholic 3.0.1.1-signed.1-signed
Stylish - Custom themes for any website 3.1.8
Tab Mix Plus 0.5.0.3
Youtube Watchmarker 3.0.2

**Comment by cmichallek** [comment]
doesnt seems to be connected to the browser version. This just changed for me from a few days ago without closing the browser. Looks like youtube is rolling out these changes per account.

**Comment by wooziwoozi** [comment]
It is 100% a "YouTube changed their layout" problem being as I was able to provide a fix through CSS. I am sure @sniklaus will fix it once YouTube switches him to the new layout.

**Comment by mikaelprag** [comment]
This happens because the extension is overriding the already existing ID "thumbnail" on the selected links with the effect of removing some YouTube default styles on them. PR #17 should solve this issue.

**Comment by sniklaus** [comment]
I am happy to announce that I have just published a new version of this extension with a fix. I am hence closing this issue, please keep me updated in case the problem still persists.
