### ISSUE TITLE
Length of Video instead of Title Shown on Info Tab

### ISSUE THREAD

**Issue by MarkRH** [sniklaus/youtube-watchmarker#29]
I've started noticing that the video lengths are showing instead of the video's title in the info window:
![image](https://user-images.githubusercontent.com/8035962/71236353-60baa300-22c4-11ea-83fd-f48b087fd647.png)

I am on Firefox 71 with 3.0.2 of the extension.  The videos with the length do not show up on YouTube as having been watched.  Probably due to the title not matching I am guessing?  What might be causing it to record the video length instead of the title?

**Comment by sniklaus** [comment]
This is the first time I have heard about such an problem and I was not able to find such issues in my watch history. Do you have any other extensions that modify Youtube? Which version of the Youtube design are you using?

**Comment by MarkRH** [comment]
I exported my database and then reset it.  I then synchronized with my browser history which was around 4,000 videos or so.  It showed the titles.  I restarted the browser and it still showed the titles.  I then exported the database again (with a new name).  I then synchronized with YouTube and has now reached as size of 10,938 and has now changed everything to the video times.

![image](https://user-images.githubusercontent.com/8035962/72609396-64087500-38ea-11ea-915f-1340dc09119e.png)

Am I hitting some database limit or something that's causing things to become wacky?

**Comment by sniklaus** [comment]
I am happy to announce that I was able to replicate and fix this problem. Thank you again for bringing this up, please let me know in case you encounter this issue again with the new version.

**Comment by MarkRH** [comment]
I was just about to comment that it seems to be fixed now.  I reset my database and ran the YouTube import.  Thanks!

**Comment by sniklaus** [comment]
I am happy to hear that, thank you for giving it another try and for confirming this!
