### ISSUE TITLE
Mark as unwatched

### ISSUE THREAD

**Issue by ddd111ddd** [sniklaus/youtube-watchmarker#3]
Is it possible to mark a video as unwatched? I'm using an extension that disables autoplay because often I just want to read comments or the description without marking the video as watched. Would be cool to have a button (at _watch?v=_).

**Comment by sniklaus** [comment]
Thank you for your feedback and my apologies for the delayed response. I just uploaded a new version that includes an overview over the recently watched movies as well as a search and the option to delete entries / mark them as unwatched.
