### ISSUE TITLE
Youtube home page displays double-height windows with grey above thumbnail

### ISSUE THREAD

**Issue by stu-champion** [sniklaus/youtube-watchmarker#30]
Starting yesterday 1/7/19 the youtube home screen is now displaying a grayed out equal height box above each video's thumbnail window when watchmarker is enabled.
![image](https://user-images.githubusercontent.com/59679717/72041506-9d910e80-3260-11ea-85e4-e51865afe158.png)
  It disappears when watchmarker is off.  What support materials would you like me to send beyond the screen capture?

**Comment by sniklaus** [comment]
Thank you for letting me know! You can have a look at #26 and follow the discussion there.
