### ISSUE TITLE
Incorrect videos being shown as "Watched" until page refresh

### ISSUE THREAD

**Issue by bsetra** [sniklaus/youtube-watchmarker#31]
When a list of videos is changed/loaded dynamically, the add-on fails to update.

Specific example: if I search YouTube for "TLOU reaction", the list shows correctly that I've seen the top several results. If I then select to filter the results by "Upload date", to find new stuff, YouTube loads correctly, yet the add-on continues to tell me I've already seen the top results even though I haven't.

If I manually refresh the entire page (F5), only then it shows correctly what I've seen.

**Comment by sniklaus** [comment]
Thank you for bringing this up! Please see #25 for additional information on this. I am happy to announce that this problem should be fixed in the new version that I just released. Please let me know in case you are still encountering this issue.
