### ISSUE TITLE
Videos are incorrectly marked as Watched

### ISSUE THREAD

**Issue by malchedial** [sniklaus/youtube-watchmarker#33]
This occurs on the Home page, after scrolling down at least 1 screenfull.  I have exported the database, grabbed a screenshot showing the URL of the video in question, and also copied the HTML using Chrome debugging tools.  I am attaching the HTML + screenshot, and can share the database with you if you need proof the video is not in the database.

[bug_example_01_html_element.txt](https://github.com/sniklaus/youtube-watchmarker/files/4212559/bug_example_01_html_element.txt)
![bug_example_01](https://user-images.githubusercontent.com/20234208/74636518-487bdd00-51bc-11ea-986f-6bacd965b748.png)

This is the third time i have seen this happen since installing the extension two days ago.  In this specific instance, the URL for the video is for a video with id "OkZxThbBDLc", and the HTML element that this extension modifies has the id "YouRect-zcw-XU5J1QY-watched".

I know this is occurring for videos I have not watched, as the three times I have noticed this so far have all been on videos uploaded within the last 2 or 3 days hence I known I haven't watched the videos in question.

Refreshing the page solves the problem - I've seen the same video turn back up in the page after refreshing, this time correctly not marking the video as watched.

For the example I am using here, the element "ytd-rich-item-renderer" contains the following: 
'&lt;a id="YouRect-zcw-XU5J1QY-watched" class="yt-simple-endpoint inline-block style-scope ytd-thumbnail yourect-watched-marker" aria-hidden="true" tabindex="-1" rel="null" href="/watch?v=OkZxThbBDLc"&gt;'

**Comment by sniklaus** [comment]
Thank you for bringing this up and for the detailed information! I am happy to announce that I just released a new version where this problem should have been fixed. I am hence closing this issue for now, please let me know in case the problem still persists. Thanks!
