### ISSUE TITLE
The "Watched" overlay doesn't work in v4.x.x

### ISSUE THREAD

**Issue by Agych** [sniklaus/youtube-watchmarker#38]
Versions 4.x.x don't work: the "Watched" overlay is not shown on the watched videos.
Had to do back to v3.0.2 where it works.
Could this be fixed?

**Comment by sniklaus** [comment]
Are you using the new or the old Youtube theme? If you don't know then feel free to post a screenshot such that I can help you debug this.

**Comment by Agych** [comment]
I'm always using the classical YouTube, the new design is just an abomination

**Comment by sniklaus** [comment]
I agree with you, but the old Youtube theme will soon no longer be available. I am afraid that I thus did not incorporate support for the old Youtube theme when rewriting this extension from scratch for the 4th version. Absolutely feel free to continue using the old version of the extension while Youtube still has the option to use the old theme. :)

**Comment by Agych** [comment]
They have been saying this for several months, however the classical YT is still here with us and many people still use it. :-) 
Moreover I think it will still remain available later on, for older browsers for example.
I would like to request adding it's support.

**Comment by sniklaus** [comment]
The old version of the extension should continue to work with the old Youtube theme and the new version of the extension was mostly to better support the new Youtube theme. Since supporting both Youtube themes would take a lot of time, I am afraid that I will not be able to do so. My apologies. Feel free to integrate the support for the old theme yourself though!

**Comment by Agych** [comment]
That's sad :-(

**Comment by sniklaus** [comment]
I understand your frustration. My time is ultimately limited though so I am afraid that I need to set priorities.

**Comment by Agych** [comment]
Well the issue could be set to lower priority for example =D

**Comment by sniklaus** [comment]
Theoretically yes, but that would practically not make much difference. :upside_down_face:
