### ISSUE TITLE
Add "HD" label to 720

### ISSUE THREAD

**Issue by Yaron10** [sniklaus/youtube-watchmarker#39]
Hello,

Is it possible to force YouTube to add the "HD" label to 720-quality videos?

Would it be possible to automatically switch to "nsfwyoutube.com" (only) if a video is restricted?

Thank you for your work.

**Comment by sniklaus** [comment]
Thank you for the suggestions! I am afraid that this extension solely focuses on marked videos as watched. While I think your suggestions would be useful to have, they would be a better fit for a different extension. I didn't find something for your first feature request, but the following should work for NSFW videos: https://addons.mozilla.org/en-US/firefox/addon/ageless/

**Comment by Yaron10** [comment]
Thank you for the detailed reply. I appreciate it.
