### ISSUE TITLE
youtube playlist wont open with add-on activated

### ISSUE THREAD

**Issue by topazz94** [sniklaus/youtube-watchmarker#4]
Hey great add-on you made. Love to use it.

But over the days I noticed a small bug. Whenever I have this add-on activated, my playlist on the home screen of youtube wont open/show more playlists. Whenever i click on "Show More"for playlists, it redirects me to my subscriptions again.

If I deactivate it, youtube lets me click on show more and it opens all my playlists again in a list.

Not sure if this is where this belongs. Had to make an account here to message you for this:)

**Comment by sniklaus** [comment]
My apologies for not having responded yet. Does this issue still persist? If so, are you using the new or the old Youtube theme? Thanks!

**Comment by sniklaus** [comment]
I have just released a new version of the extension where this probvlem should no longer occur. I am hence closing this issue, please feel free to reopen it in case the problem prevails. Thanks!
