### ISSUE TITLE
Suggestion: shrinking the script to fit in GreaseMonkey

### ISSUE THREAD

**Issue by DonaldTsang** [sniklaus/youtube-watchmarker#40]
It would be great if the code can be stored in GreaseMonkey.
Doubly so if it can be packed together with other programs like https://github.com/amitbl/blocktube and others.

**Comment by sniklaus** [comment]
Thank you for the suggestion! I am afraid that my time is limited and I will not be able to support Greasemonkey, my apologies. If someone else wants to add this feature, I would be happy to link to their implementation in the readme.
