### ISSUE TITLE
Encountered a bug between Watchmarker for YouTube and YouTube Studio

### ISSUE THREAD

**Issue by DJGoo** [sniklaus/youtube-watchmarker#45]
Hey, I discovered the other day that something Watchmarker does makes it so when you go into YouTube Studio to manage uploads (and a few other interfaces in Studio) the interfaces act as if they are offline.
I went through all of my extensions one by one and it is 100% Watchmarker unfortunaly.
I don’t know why it causes this issue in specific, but I discovered an easy solution. 
As a user, I appear not to be able to change Watchmarkers site access, but if the site access was changed from allowing:
```
 "*://*.youtube.com/*"
```
to 
```
"*://www.youtube.com/*"
```
or if a block was added for
```
"*://studio.youtube.com/*"
```
it wouldn’t run on the Studio pages at all.

This solution would effectively solve the problem without needing to find out the exact cause of this bug.

I have also used this extension for an extended period of time in both Firefox and Chrome and I encountered another bug relating to the new layout of YouTube messing with the watched labels which I was able to solve with a small custom ‘theme’ applied with the extension Stylus to fix the layout, but I have not tested this issue with Studio in Firefox.

I hope the potential solution I’ve provided helps, and thanks so much for making this extension. Watchmarker is one of my must-have extensions now and is one I recommend to all my friends, I really appreciate the work that goes into it.

_PS: I also sent this in an email, sorry, I hadn't realised GitHub was an option at the time._

**Comment by sniklaus** [comment]
Thank you for bringing this up and for going as far as to suggestion a solution! I made the changes in e078c25eb59079463b66b44cc75202b00964d972 and updated the extension on the Firefox an Chrome store (it will take a while for the new version in Chrome to be approved).

Feel free to elaborate on the bug with the new layout of YouTube messing with the watched labels if you want. I would be happy to fix any such issues directly in the extension such that all users can make use of them. :+1:
