### ISSUE TITLE
Can you make Watchmarker so that it shows Youtubes' red bar instead of a "watched" overlay but just forever?

### ISSUE THREAD

**Issue by ars4l4n** [sniklaus/youtube-watchmarker#46]
Youtubes' red bar that shows you far you've made it in an unfinished video is actually useful so it would be nice if you extended the lifetime of that bar with your addon for those users who prefer that variant
I haven't found another app so far that does this either.

(Another idea is to use both: Videos that are partially watched, get the red bar and finished ones get the "watched" overlay. This makes them visually more distinguishable. I just think of this as something optional. 
What I personally prefer is a layout with red bars and no dimming over the thumbnails because I don't want the site to make unwatched videos stick out in a way that tells me "You have to watch these and not those!" because I may not like those particular unwatched videos.
Dimming the thumbnails also makes me tend to not want to look through videos for rewatching even though some may be worth it.
The dimming does definitely make sense, especially, if you mark good videos with a _like_ so that you have them in a list anyway, but I just feel more drawn to how I described it)

Best Regards,
ars4l4n

**Comment by sniklaus** [comment]
Thank you for the suggestions! I agree that they would be generally good to have as an option. However, I would need to be able to figure out how much of a video has been played to implement this video which is not possible for videos that have been watched a long time ago. So if someone installs the Youtube Watchmarker and uses the built-in sync with the browser history and the history on YouTube, the information about how much of a video has been played is not accessible. As such, the behavior would be inconsistent as it is unclear how the marking should be done in such cases. I am thus sorry that I am unable to implement this properly.

**Comment by ars4l4n** [comment]
>I would need to be able to figure out how much of a video has been played to implement this video which is not possible for videos that have been watched a long time ago.
So if someone installs the Youtube Watchmarker and uses the built-in sync with the browser history and the history on YouTube, the information about how much of a video has been played is not accessible. As such, the behavior would be inconsistent as it is unclear how the marking should be done in such cases. 

What about doing it like this then: 

Use the video-position-indicator Youtube provides for the first couple months, let the extension save it and create its own indicator after those months, and this should be implemented as an option with a popup that tells the user it's not going to work as intended at first but will do so after a few months when you keep it turned on

**Comment by sniklaus** [comment]
Possible, but in my opinion not worth the implementation effort due to it not being a solution that provides a consistent user experience. If you want to take the time to implement this feature, I would be happy to point to such a fork in the readme though. :+1:

**Comment by ars4l4n** [comment]
Wanted to add to that that the user experience is by default inconsistent
so this feature would still lead to a net consistency gain
I'm not a programmer unfortunately :/ and can only do some Autohotkey
scripts ^^"
I'm just a guy who searches for software and sometimes contacts devs

Am Mi., 18. Nov. 2020 um 00:10 Uhr schrieb Simon Niklaus <
notifications@github.com>:
