### ISSUE TITLE
Try implementing this to youtube music

### ISSUE THREAD

**Issue by mic345556** [sniklaus/youtube-watchmarker#49]
I found on reddit that a lot of people want similar feature on youtube music platform.

-addon for youtube and youtube music should share same database (watched history)
-addon on youtube music should remove (instead of marking as watched) any song from radio queue that has been listened before

love the work.

**Comment by sniklaus** [comment]
Thank you for this suggestion! I have to kindly turn down this request though, my apologies. Your suggestions definitely would greatly enhance the experience on Youtube Music, but I am afraid that I do not have the time/energy to extend the scope of this extension to such a significant degree.
