### ISSUE TITLE
3.0.1 in Firefox 57b5: Can't Click Advanced Setting on Edit Video Screen if Enabled.

### ISSUE THREAD

**Issue by MarkRH** [sniklaus/youtube-watchmarker#5]
Uploaded a YouTube Video and wanted to change the category and I couldn't get Advanced Settings to do anything. Turns out if I disabled YouTube Watchmarker, then the link started working. Happens in both 56 and 57beta. Weird.

Screenshot of what I'm talking about: https://i.imgur.com/qiIqRs1.png

Anyway it is awesome to get better track of what I've watched. At least I know the reason why it wasn't working. I went to IE 11 to change the category LOL.

Thanks for your work.

**Comment by sniklaus** [comment]
My apologies for not having responded yet and thank you for bringing this up. The fix should actually quite easy and I just wanted to do it before I comment. I have been busy though and hence didn't find the time. I just wanted to mention that I didn't forget about it though.

**Comment by sniklaus** [comment]
This should no longer be a problem with the new version, I am hence closing this issue. Thank you for bringing this up and please keep me updated in case the problem continues to prevail.
