### ISSUE TITLE
ability to mark whole channel as watched

### ISSUE THREAD

**Issue by perseusbiscuitsakira** [sniklaus/youtube-watchmarker#51]
is their a way to mark all videos (currently) on a channel as watched? (I don’t have youtube history turned on, so no history to import)

**Comment by sniklaus** [comment]
Not currently, it sounds like a useful feature though. I am afraid that I currently do not have the time to implement this but I will leave the issue open such that I can revisit this again in the future.

In the meantime, you could give the synchronization with the browser history a try.

**Comment by perseusbiscuitsakira** [comment]
that's fine, I've watched alot of channels over the last decade, no way history has all of that, I'll just leave channels playing when I'm not at my machine, doe's anyone know of any tricks to cause the next video in a playlist to play instantly and skip or anything like that?

**Comment by s3thGG** [comment]
please add mark all feature for playlists when you do :)

**Comment by sniklaus** [comment]
This is not the most convenient way, but it works and it allows you to mark everything in a channel as watched, everything in a playlist as watched, and many more by using `youtube-dl`. First, use the following command and adjust the URL accordingly to capture the content that you want to have marked as watched.

```
youtube-dl --ignore-errors --flat-playlist --dump-json https://www.youtube.com/user/XboxAhoy/videos > archive.txt 
```

Then inspect the `archive.txt` file to check that it only contains the videos that you expect. You can then use the following Python script to convert the `archive.txt` into an `archive.database` that you can import in the settings of the Youtube Watchmarker.

```python
import base64
import json
import time

objVideos = []

with open('archive.txt', 'r') as objFile:
    for strVideo in objFile.read().splitlines():
        try:
            objVideo = json.loads(strVideo)
        except:
            continue
        # end

        objVideos.append({
            'strIdent': objVideo['id'],
            'intTimestamp': int(round(time.time() * 1000.0)),
            'strTitle': objVideo['title'],
            'intCount': 1
        })
    # end
# end

with open('archive.database', 'w') as objFile:
    objFile.write(base64.b64encode(json.dumps(objVideos).encode('utf-8')).decode('utf-8'))
# end
```
