### ISSUE TITLE
Suggestion: "Not interested" videos block

### ISSUE THREAD

**Issue by CorneliusBaku** [sniklaus/youtube-watchmarker#55]
Hi... can you make Watchmaker to block also videos marked as "Not interested"?

**Comment by sniklaus** [comment]
Thank you for the suggestion! What do you mean by "block"?

**Comment by CorneliusBaku** [comment]
"Block" means what Watchmaker is doing by marking watched videos.

**Comment by sniklaus** [comment]
I briefly looked into this but am afraid that Youtube does not expose the information of whether or not you have marked a video as "not interested" previously. So the only way to implement this feature is to hook into the "not interested" button and intercept it to add the respective video to the database. However, this feature seems pretty niche and I am sorry that I am unable to invest time into supporting this request. My apologies.
