### ISSUE TITLE
Suggestion: Black & White Thumbnails for watched videos

### ISSUE THREAD

**Issue by scarface52** [sniklaus/youtube-watchmarker#58]
In the dark mode, I find it a bit hard to tell if the video was watched or not. An option to make thumbnails black&white might be useful. Maybe darkening the video title as well could help a bit. Something like this:

![Ekran görüntüsü 2021-03-03 040506](https://user-images.githubusercontent.com/71343424/109738312-a10bf580-7bd8-11eb-8c04-4aff738144b8.png)

**Comment by sniklaus** [comment]
Great suggestion, I just added this feature in the newest version (it is configurable in the options).

**Comment by scarface52** [comment]
Great job! Thanks for taking your time.
