### ISSUE TITLE
Import asks for .database file needs .txt file

### ISSUE THREAD

**Issue by ghost** [sniklaus/youtube-watchmarker#59]
when using import file explorer needs to be set to all files instead of current default .database to accept an exported txt file.

**Comment by sniklaus** [comment]
As shown below, the export function exports a `.database` file.

https://github.com/sniklaus/youtube-watchmarker/blob/740c361662f606ac3b75bfbc5ce4269b952f39c9/background.js#L260

The import function thus imports `.database` files by default. How come the database you are trying to import has a `.txt` ending?

**Comment by sniklaus** [comment]
Are you using Chrome or Firefox? The behavior in Firefox is as expected as shown below, but I haven't tried Chrome.


https://user-images.githubusercontent.com/1238034/117601298-d82fe300-b102-11eb-9d53-2af29d5827c4.mp4

**Comment by s3thGG** [comment]
yes this happens on chrome, but not firefox

**Comment by sniklaus** [comment]
Thanks for letting me know! I'll try to fix this with the next version, but not sure whether Chrome will let me. :upside_down_face:

**Comment by s3thGG** [comment]
thanks :D

**Comment by rossc719g** [comment]
Seeing this on my chrome machines too.
If chrome won't let you change the exported file extension, maybe just accept .txt as a valid extension on chrome?
