### ISSUE TITLE
history empty & not working anymore since update to ff 57

### ISSUE THREAD

**Issue by Fuchsinger** [sniklaus/youtube-watchmarker#6]
worked very well until i updated to ff 57. totally loved it when it worked.
since updating to 57 my history, database and searches are empty. and sadly no more "watched" videos.
when i click on "synchronize" (in both options) a unclickable message saying "synchronizing with history" appears but nothing else happens (waited 30 minutes to be sure) until i reload or close the tab. 
the search wheel at the buttom right is constantly turning but not finding anything.
already tried resetting the database, reinstalling the addon, overinstalling the browser and restarting the mac (os 10.12.6). it's just not working anymore.
on my older mac with el capitan this great addon strangely still works after the update to ff 57.
any ideas?

<img width="742" alt="bildschirmfoto 2017-11-28 um 00 47 44" src="https://user-images.githubusercontent.com/34045688/33317457-874f9db4-d437-11e7-9b55-94167573a5d2.png">

**Comment by Fuchsinger** [comment]
SOLVED: https://support.mozilla.org/en-US/kb/reset-preferences-fix-problems

**Comment by sniklaus** [comment]
Thank you for keeping us updated, and my apologies for not having looked into this myself yet.

**Comment by spider3000** [comment]
Not sure if it's allowed to comment on a closed issue, however I had the same issue and finally got around to solving it. I'm currently running Waterfox 56.2.9 with a 10+ years old Firefox profile.
After much trial and error deleting different files and folders from the browser profile, I've found that deleting (or renaming just in case) the file `storage.sqlite` in the profile folder fixes the issue, and so far I haven't noticed anything else being broken or missing by deleting that file.
Maybe this will help someone else still looking for a fix.

**Comment by sniklaus** [comment]
Awesome, huge thanks for sharing your findings with us!
