### ISSUE TITLE
Suggestion: In extension toolbar icon context menu enable options button (Chrome)

### ISSUE THREAD

**Issue by ghost** [sniklaus/youtube-watchmarker#60]
For Chrome extensions you can right click an extension and get a menu which has an options button, in Watchmarker the button is greyed out, this led me to not be able to find the options page at first because I had not left clicked it yet and assumed there wasn't one for a while, I think other people might sometime have this problem. while not essential if you could link this options button to the main extension page that would be very helpful!

**Comment by s3thGG** [comment]
Attached, image of extension with and without option button.
![Image 1](https://user-images.githubusercontent.com/76197695/215145156-0b21868c-6ba9-4b5e-8250-b3a7c44a709c.png)
![Image 2](https://user-images.githubusercontent.com/76197695/215145168-442baab3-0b0a-4243-bfa1-bbfaaebc3018.png)
same deal on pinned icon right click.

**Comment by sniklaus** [comment]
Got it, thanks for clarifying!

**Comment by sniklaus** [comment]
I will fix it tonight and release a new version. Please feel free to reopen this issue should the problem persist after I released the next version. Thanks again for bringing this up!
