### ISSUE TITLE
clicking search button causes it to animate rapidly between two icons

### ISSUE THREAD

**Issue by MinuteAd8502** [sniklaus/youtube-watchmarker#64]
When I click on search icon to search for some previously watched video icon rapidly animates between setting icon and itself.
Did not notice that on earlier versions.
Also even in earlier versions noticed wrong videos being shown as watched on right sidebar of Youtube, in related videos etc.

**Comment by sniklaus** [comment]
Thanks for letting me know! I just fixed it in 427e6b201d5de6fae70f9e9d3644deb9262246cc and this will land in the next update of the extension (but I am afraid that I do not know when I will be pushing the next update, sorry).
