### ISSUE TITLE
"Add Support For youtube-dl Database File" Feature Request !

### ISSUE THREAD

**Issue by Goyp95** [sniklaus/youtube-watchmarker#67]
Can u make this App works with youtube-dl --download-archive file as database, basically it's just this inside .txt file [ youtube zv9-kZ0DN-w ] per line, if not do you knows how to convert this file to watchmarker database file.

**Comment by sniklaus** [comment]
This should do the trick for you: https://github.com/sniklaus/youtube-watchmarker/issues/51#issuecomment-922645881
