### ISSUE TITLE
Suggestion: History Trends Unlimited Import

### ISSUE THREAD

**Issue by ApertureSc1** [sniklaus/youtube-watchmarker#71]
I have my internet history starting from 2013 with every youtube video I've ever watched using History Trends Unlimited and I wanted to know if you could add functionality to import search results from the extension, I can easily grab all the youtube links using the wildcard function `https://www.youtube.com/watch?v=*`

Please and thank you.

Examples of the exported file below, shouldn't be that hard to add functionality for it with this information provided based on my previous coding experience
![Screenshot_11](https://user-images.githubusercontent.com/90119598/133750980-1c64270c-69dc-4424-a6f6-cef3aaffd617.png)
![Screenshot_12](https://user-images.githubusercontent.com/90119598/133750982-d0ba7cb1-e0fc-468c-abd6-02e84433f6b3.png)
.

**Comment by sniklaus** [comment]
Since you are familiar with coding, this should be easy for you to do yourself. :slightly_smiling_face: 

You can write a script that takes the videos from History Trends Unlimited and converts them into the database format used to import/export the database in the Youtube Watchmarker. You can take a look at this script as an example, which does the same for Google Takeout: https://github.com/janpaul123/youtube-takeout-to-watchmarker

It would be great if you could share your findings/script here for others to use as well. :+1:

**Comment by Glados95** [comment]
I spent a few hours trying to do so, I'm not familiar with the specific database file format you're using, I am familiar with parsing raw data line by like like what I showed in those images.

Basically all you'll need to do is input _URL Host,\[strIdent\]_ _Page Title\[strTitle\]_ and _Visit Time (ms)\[intTimestamp\]_ and you can either ignore duplicate lines or count them with intCount if I'm reading the code correctly, I've never written code in Rust.

**Comment by ApertureSc1** [comment]
I spent a few hours trying to do so, I'm not familiar with the specific database file format you're using, I am familiar with parsing raw data line by like like what I showed in those images.

Basically all you'll need to do is input _URL Host\[strIdent\]_ _Page Title\[strTitle\]_ and _Visit Time (ms)\[intTimestamp\]_ and you can either ignore duplicate lines or count them with intCount if I'm reading the code correctly, I've never written code in Rust and it should work.

**Comment by sniklaus** [comment]
The good thing is that you don't need to use Rust, almost all programming languages will do. For example, in JavaScript you can create an array of dictionaries that has the following structure.

```
[{
    'strIdent': 'youtube_video_id_consisting_of_11_characters',
    'intTimestamp': epoch_time_at_which_the_video_was_watched,
    'strTitle': 'title_of_the_video_which_can_be_an_empty_string',
    'intCount': how_often_the_video_has_been_watched
}, {
    'strIdent': 'B3uws4cLcFw',
    'intTimestamp': 1632071242026,
    'strTitle': 'Attention for RNN Seq2Seq Models (1.25x speed recommended)',
    'intCount': 1
}, {
    ...
}]
```

So you can just take the data from History Trends Unlimited and convert it to a structure like this. And then you convert it to a JSON format and then apply a Base64 encoding. Voila, you have a database format that can be imported into the Youtube Watchmarker, no knowledge about the Youtube Watchmarker extension necessary. :slightly_smiling_face:

**Comment by sniklaus** [comment]
This may help you: https://github.com/sniklaus/youtube-watchmarker/issues/51#issuecomment-922645881

**Comment by ApertureSc1** [comment]
The exported links contained a few occurrences of random links to to other sites being mixed in
Like;

- https://www.google.com/sorry/
- - https://www.google.com/sorry/
- - https://www.google.com/sorry/
- - https://www.google.com/sorry/

**Comment by ApertureSc1** [comment]
Using your example I was able to easily import EVERYTHING

I had to remove a few lines from the results .tsv file though, it appears the wildcard didn't work as perfectly as I thought

The exported links contained a few occurrences of random links to to other sites being mixed in, the problem links are provided below;
- https://www.google.com/sorry/
- https://ytmp4.top
- https://twitter.com
- https://www.youtube.com/results?search_query=
- https://steamcommunity.com
- https://www.google.com
- https://www.deviantart.com
- https://www.convertinmp4.com
- https://duckduckgo.com
- https://webcache.googleusercontent.com
- https://ipv4.google.com
- https://t.umblr.com
- https://www.youtube.com/attribution_link
- http://webcache.googleusercontent.com/
- https://www.facebook.com/
after removing these links using notepad++ `bookmark line > {link} > mark all` (do this for every website listed above)
then  `search > bookmark > remove bookmarked lines` the code worked perfectly.

Here's the code I used, anyone else can feel free to use it to import their history if they use History Trends Unlimited.

```python
import urllib.parse as urlparse 
import base64
import json
import csv
objVideos = []
lineInt = 0
with open("history_full.tsv", encoding='utf-8') as file:
    tsv_file = csv.reader(file, delimiter="\t")
    for line in tsv_file:
        lineInt += 1
        print(str(lineInt))
        url_data = urlparse.urlparse(line[0])
        query = urlparse.parse_qs(url_data.query)
        video = query["v"][0]
        try:
            objVideos.append({
                'strIdent': video,
                'intTimestamp': int(float(line[3])),
                'strTitle': line[7].replace(" - YouTube", ""),
                'intCount': 1
            })
        except IndexError:
            objVideos.append({
                'strIdent': video,
                'intTimestamp': int(float(line[3])),
                'strTitle': 'Unknown',
                'intCount': 1
            })
            print(objVideos[-1])

with open('archive.database', 'w', encoding="utf8") as objFile:
    objFile.write(base64.b64encode(json.dumps(objVideos).encode('utf-8')).decode('utf-8'))```

**Comment by sniklaus** [comment]
This is awesome, thank you for sharing your script/findings!
