### ISSUE TITLE
Youtube shorts don't get marked as watched

### ISSUE THREAD

**Issue by scarface52** [sniklaus/youtube-watchmarker#73]
The URL path for Youtube shorts has been changed to be different from regular videos.

They start with `/shorts/` instead of `/watch?v=` which seems to have caused them to not appear as watched in UI.

**Comment by VcSaJen** [comment]
Sample channel with shorts:
https://www.youtube.com/channel/UC6j5fwiGHN9gCkxUcfcVcKQ/videos

**Comment by scarface52** [comment]
The change appears to be reverted.
