### ISSUE TITLE
YouTube Shorts not marked

### ISSUE THREAD

**Issue by Trelligan** [sniklaus/youtube-watchmarker#76]
YouTube's brand new Shorts format are not being marked by YouTube Watchmarker.
   Please update YouTube Watchmarker to handle YouTube Shorts.
   I understand that this is a new format, and you may want to wait for further changes before you invest the time chasing YT's frequent format changes.
   I voted with my wallet, as you'll see.

   Thank you for an excellent product that has enhanced my YT watching.

**Comment by lane333** [comment]
having  the same problem  and now  shorts  seem to be prolific  and  its not  marking them...please help

**Comment by fstoll3** [comment]
I have the same problem.

**Comment by lane333** [comment]
not sure of  the effetiveness of this website....no response  or fix  from creator...i still like  the extension  however  the shorts are quite annoying

**Comment by Lightjohn** [comment]
If you don't care at all for shorts: I have this solution:
https://letsblock.it/filters/youtube-shorts
It will remove them all

**Comment by sniklaus** [comment]
> not sure of the effetiveness of this website....no response or fix from creator

I am very well aware of what people post, I just don't have time right now to look into this. You are very welcome to address this yourself and open a pull request. :+1:

**Comment by lane333** [comment]
thank you LightJohn i'll try  that  until snikalus has time  to look into  it

**Comment by qstar-inc** [comment]
I have a different problem; a newly released short was marked as watched even though I didn't watch it. It is not on the Watchmaker's list of history either.

**Comment by mlb-fan** [comment]
If [this update](https://github.com/sniklaus/youtube-watchmarker/pull/83) fixes this issue finally, can it please get merged and then update the Firefox plugin page.

**Comment by sniklaus** [comment]
I just issued a new version (4.2.0) of the extension, it is available for Firefox right now and currently under review for Chrome. Huge thanks to @Yentis for contributing this feature!

**Comment by Lightjohn** [comment]
Thanks for that :)
