### ISSUE TITLE
Unwatched videos marked as watched

### ISSUE THREAD

**Issue by AstoranSolaire** [sniklaus/youtube-watchmarker#77]
The extension is increasingly marking videos I have not watched as being watched; I know this to be the case as they are always recently uploaded videos... not that I have any idea how all of this works but it seems to me as if there is some sort of link to a channel's most recent video, so if I have clicked on and watched a channel's most recent video at any point, whenever they release another one the latest one will always be marked as watched.

**Comment by JustAnOkapi** [comment]
duplicate of #56
