### ISSUE TITLE
Extension is not working and has been removed from the Chrome Store

### ISSUE THREAD

**Issue by perseusbiscuitsakira** [sniklaus/youtube-watchmarker#79]
Extension (Version 4.1.0) is not marking watched videos on Chrome (Chromium: 100.0.4896.60) and the Chrome Store page has been removed

https://chrome.google.com/webstore/detail/watchmarker-for-youtube/

**Comment by sniklaus** [comment]
Looks like the store now needs the full link: https://chrome.google.com/webstore/detail/watchmarker-for-youtube/pfkkfbfdhomeagojoahjmkojeeepcolc

I just tried Chromium `Version 100.0.4896.60 (Official Build) snap (64-bit)` and didn't encounter any obvious issues. Maybe try reinstalling?

**Comment by perseusbiscuitsakira** [comment]
Just updated to 100.0.4896.75 and it's working now
