### ISSUE TITLE
remove watched video ONLY from extenson database

### ISSUE THREAD

**Issue by nijazm** [sniklaus/youtube-watchmarker#92]
I hate when I accidentally open some video, and when I want to remove it from extension database, it says that it is removing it from YouTube's history. And because I have slow Internet, it is so slow. A anyways do not have youtube history enabled. So I'd like it to skip that slow step. Or add it as additional option.

**Comment by sniklaus** [comment]
But the video will still likely be marked as watched on Youtube's side of things, and since the Youtube Watchmarker automatically adds everything that Youtube thinks has been watched back to the database the video would eventually be marked as watched again. Seems like removing it from Youtube's watch history is a requirement. :thinking:

**Comment by nijazm** [comment]
Well, not if we don't have enable youtube history in google account, and not enabled _Mark a video as watched once it has the official Youtube watched badge._ and _Mark a video as watched once it appears in Youtube's watch history_. At least if there would be advanced option to skip that step or skip button when it starts.

**Comment by sniklaus** [comment]
So if

- "Mark a video as watched once it has the official Youtube watched badge" is disabled which is enabled by default, and
- "Mark a video as watched once it appears in Youtube's watch history" is disabled which is enabled by default

and if a video is ought to be removed from the history per a user's request then

- the video should not be tried to be remove from Youtube's watch history, but
- the video should be removed from the browser's history still.

Seems like a very specific feature that may have limited use to the overall user base. I understand that it would be very useful to you, but every piece of logic that I add not only takes time adding it but also time to maintain. :thinking:

**Comment by nijazm** [comment]
Forgot to mention, _Mark a video as watched once it appears in Youtube's watch history._ is also disabled by me.
Yes, very specific, but biggest issue to me is actually combination of slow Internet, and broken touchpad, so I sometimes easily open wrong video. But, not a big deal.

**Comment by sniklaus** [comment]
I will implement it as outlined in #116, thank you for your patience.
