### ISSUE TITLE
Custom CSS for watched videos

### ISSUE THREAD

**Issue by TinJoy59** [sniklaus/youtube-watchmarker#93]
First off, thank you for creating this. 

As the tittle suggest, allow for the injection of custom CSS. Ever since thumbnail progress bar has been around, I used custom CSS to mimic what you do with your styling, only with blue tint. I just prefer blue. My vision is used to blue and now I'm adding it to your styling via another extension.

So are you willing to add custom CSS field for people that don't an to utilize a whole other extension?

**Comment by GaabluhnMowd** [comment]
Any timeline on when this feature might be added?

**Comment by sniklaus** [comment]
This has, more or less, been added to the newest release. That is, it is there but not exposed to the average user. Instead, if you want to change the CSS you have to do so in the debugger. Specifically, navigate the local storage of the extension and edit the CSS in there (see videos below). The rationale behind this is that a user who knows how to adjust the CSS is probably also verse enough to open the debugger to change it there.

Where to find the local storage of an extension in Firefox:
https://github.com/sniklaus/youtube-watchmarker/assets/1238034/24c53873-654d-4e41-9bd5-8d5d7778a84b

Where to find the local storage of an extension in Chrome:
https://github.com/sniklaus/youtube-watchmarker/assets/1238034/f2ced88a-034f-46b8-acee-888796bc7996

**Comment by sniklaus** [comment]
For anyone else interested in modifying the CSS, make sure to also read/do this: https://github.com/sniklaus/youtube-watchmarker/issues/141#issuecomment-2641817686
